### ISSUE TITLE
Release on PyPI

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/pydsdlgen#17]
Do we not want to make the pydsdlgen package available on PyPI? We have the organization set up there: https://pypi.org/user/uavcan/

On a somewhat related note, this file is authored by an impostor:

https://github.com/UAVCAN/pydsdlgen/blob/fb21f6a4d58c13d36a8da700f59500b4edd565a0/setup.py#L6

**Comment by thirtytwobits** [comment]
I was waiting until I had this flushed out a bit more. Specifically I wanted to get though a full C++ generation pass in libuavcan before pushing to Pypi. That said, I could downgrade the version number to a pre-release 0.1.0 and push if you are interested in using it.

**Comment by pavel-kirienko** [comment]
I am already using it in pyuavcan, although I had to install it manually though setup.py. I am fine within doing it this way for now, so there's no rush.
