### ISSUE TITLE
Custom template filters

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/pydsdlgen#20]
It should be possible to add custom filters and possibly other entities to the Jinja environment.

@thirtytwobits would it be appropriate to just add a property `Generator.environment: Environment` to expose `Generator._env`?

**Comment by pavel-kirienko** [comment]
> would it be appropriate to just add a property

Come to think of it, this might be undesirable from the encapsulation standpoint. Perhaps the constructor of Generator could be extended with a few additional optional parameters for passing custom filters and tests?

**Comment by thirtytwobits** [comment]
done
