### ISSUE TITLE
File post-processing

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/pydsdlgen#33]
Would be nice to have:

- Set access permissions for generated files to 0444 (read-only for all). Handle this properly when overwriting existing files.
- Strip trailing newlines after generation (disabled by default).
- Do not permit more than X consecutive blank lines (X is user-configurable, infinity by default).
- Enforce exactly one blank line at the end of the file (disabled by default).

The last three could be conveniently delegated to the user code if there was a way to pass a transformer function `(str) -> str` into the generator which is then applied to every generated file before its content is written on disk.

**Comment by thirtytwobits** [comment]
access permissions sounds reasonable but I'm reticent to implement the other features. First off, Jinja provides pretty fine-grained [whitespace control](http://jinja.pocoo.org/docs/2.10/templates/#whitespace-control) so I don't think we'll authored templates should need any further processing. Second, adherence to a standard should be provided by a language specific linter (e.g. pylint or clang-format).

**Comment by thirtytwobits** [comment]
Here's what I want to do with this:

1. Add a formatter plugin API to allow running autopep8, clang-format, etc as a post-processing step.
1. Set access permissions to 0444 after the generation and reformat steps have been completed.
1. Add a `--force,-f` argument.
1. Fail when attempting to generate over an existing file unless the `--force` argument is provided.

**Comment by thirtytwobits** [comment]
Closing this issue in favor of #37 and #38

**Comment by thirtytwobits** [comment]
Re-opening this issue because nobody likes dealing with Jinja whitespace control.

**Comment by thirtytwobits** [comment]
@pavel-kirienko what exactly do you mean by:

> Strip trailing newlines after generation.

and how is that different than the other two requirements for whitespace control?

**Comment by thirtytwobits** [comment]
Okay. I'm not going to give you  everything you asked for but I'll give you the ability to do the whitespace post processing yourself. If you look at [ChunkPostProcessor](https://github.com/thirtytwobits/pydsdlgen/commit/79d5060720417dac4fb6ba86870d0ac1ad8938cb#diff-bbd446b75f83295b070695d1d47abc21R62)  you can see how I've enabled this. I still think what you want is a hack to work around poorly authored templates but whatever.

**Comment by pavel-kirienko** [comment]
> what exactly do you mean by:
> > Strip trailing newlines after generation.

I meant the removal of extra blank lines at the end of the file.

**Comment by pavel-kirienko** [comment]
> If you look at ChunkPostProcessor you can see how I've enabled this.

What if a chunk ends with a trailing space, which is then followed by another non-whitespace chunk? If I remove the trailing whitespace, the chunks will be concatenated which may break the generated code.

**Comment by thirtytwobits** [comment]
ah, pshaw. You and your pointing out logical flaws. Okaaaay. I'll give you a line processor. But I won't like it.
