### ISSUE TITLE
File permissions and overwrite protection

### ISSUE THREAD

**Issue by thirtytwobits** [UAVCAN/pydsdlgen#38]
Set access permissions to 0444 after the generation and reformat steps have been completed.

**Comment by pavel-kirienko** [comment]
> Add a --force,-f argument.

Is there a valid scenario where one wouldn't want to use this flag? Generated files are to be either completely unmodified, in which case they can be rewritten without the risk of unrecoverable loss of information, or they are version-controlled (I foresee this could be useful in high-integrity applications), in which case the change can be rolled back if necessary. Maybe `--force` should be the default behavior?

**Comment by thirtytwobits** [comment]
Closing this since we reopened #33
